# Generated by Django 2.0.3 on 2018-09-23 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('tipo', models.IntegerField(choices=[(0, 'disponível'), (1, 'reservado'), (2, 'em falta')])),
                ('descricao', models.TextField(blank=True)),
                ('regional', models.BooleanField(default=False, verbose_name='regional')),
                ('internacional', models.BooleanField(default=False, verbose_name='internacional')),
                ('image', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notícia',
                'verbose_name_plural': 'notícias',
            },
        ),
    ]
