# Generated by Django 2.0.3 on 2018-09-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodnews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='news',
            name='regional',
        ),
        migrations.AlterField(
            model_name='news',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Regional'), (2, 'Internacional')]),
        ),
    ]
