# Generated by Django 2.0.3 on 2018-09-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodnews', '0002_auto_20180923_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='internacional',
        ),
        migrations.AddField(
            model_name='news',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
    ]
