# Generated by Django 2.0.3 on 2018-09-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodnews', '0003_auto_20180923_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Regional'), (2, 'Internacional')], verbose_name='É uma notícia'),
        ),
    ]
