# Generated by Django 2.0.3 on 2018-09-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodnews', '0004_auto_20180923_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Adicionar imagem'),
        ),
    ]
